### ISSUE TITLE
Sidenav

### ISSUE THREAD

**Issue by Dragonbabe** [Dragonbabe/Mamma-Mia#2]
Add a side nav to store favorite event on local storage. Make a remove button for each events and a Clear button at the bottom

**Comment by ddhoang21** [comment]
I misunderstood what side-nav was. It's not a popup where we can store our "saved events". It only makes the nav-bar links (ex: Home, Contact, Portfolio) into a dropdown when making the screen smaller. So we can't use that for our favorite events.
In order to fix this, I've decided to go with our initial idea of having the saved events on the left side of our main page by using the collapsible section in materialize.
